version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=your_db_name
      - NODE_ENV=development
    depends_on:
      - db

  db:  # This is your local postgres service
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
